export const GET_PAYMENT_DATA = "GET_PAYMENT_DATA";
export const SEARCH = "SEARCH";
export const CREATE_NEW_PAYMENT = "CREATE_NEW_PAYMENT";
export const DELETE_PAYMENT = "DELETE_PAYMENT";
export const EDIT_PAYMENT = "EDIT_PAYMENT";
